rx = comm.SDRuReceiver(...
                    'Platform','X310', ...
                    'OutputDataType','double', ...
                    'MasterClockRate',200e6, ...
                    'DecimationFactor',400, ...
                    'Gain',35, ...
                    'CenterFrequency',3.9e9, ...
                    'SamplesPerFrame',4000)

spectrumScope = dsp.SpectrumAnalyzer('SampleRate',200e6/100); 
spectrumScope.ReducePlotRate = true;               

time = 0;
frameduration = (rx.SamplesPerFrame)/(200e6/100); 

while time < 1000
 [data,len] = step(rx); 
 %timeScope([real(NormalizedData),imag(NormalizedData)]); 
 spectrumScope(data); 
 time = time + frameduration; 
end